title: "Mehdi Akbarian"
baseurl: ""

first-name: 'Mehdi'
last-name: 'Akbarian Rastaghi'
job-title: 'Computer  Science Student at UofA and Founder of <a href="https://sakkku.cloud/En">SAKKU Cloud Platform</a>'
# blurb-about-self: 'Advisor: <a style="font-weight: bold;" href="http://lampwww.epfl.ch/~odersky/">Martin Odersky</a>'
profpic: '/resources/img/profilepic.jpg'
profpic-retina: '/resources/img/profilepic@2x.jpg'
twitter: mehdiakbn
email: 'makbaria@ualberta.ca'
github: 'makbn'
location: 'Virgo Supercluster'
#location-url: "https://www.google.com/maps/place/46%C2%B031'06.3%22N+6%C2%B033'44.6%22E/@46.5188495,6.5633963,18z/data=!4m2!3m1!1s0x0:0x0"

# For syntax highlighting, the primary programming langauge you intend to use in
# blog articles. By default, Google's prettify will be used for this programming
# language, as per the instructions here: https://github.com/google/code-prettify
# For example, if I indicate `scala`, all pre/code blocks will have the `lang-scala`
# class added to the markup, triggering prettify to highlight the syntax as Scala.
primarylanguage: java
# To sidestep the default language for syntax highlighting set here, you can be
# explicit in your blog articles with the langauge you'd prefer to use. E.g.,
# <pre>
#   <code class="prettyprint lang-ruby">
#    ..ruby code here...
#   </code>
# </pre>

# categories:
#   blog:
#     permalink: /blog/:title.html

# Settings for blog RSS feed
name: "Mehdi Akbarian"
description: ""
url: "https://makbn.giithub.io"

permalink: /:categories/:title.html
# markdown: redcarpet
highlighter: null

sass:
  style: compressed

livereload: true
