title: "Mehdi Akbarian"
baseurl: ""

first-name: 'Mehdi'
last-name: 'Akbarian Rastaghi'
job-title: 'Computer  Science Student at UofA and Founder of <a href="https://sakkku.cloud/En">SAKKU Cloud Platform</a>'
# blurb-about-self: 'Advisor: <a style="font-weight: bold;" href="http://lampwww.epfl.ch/~odersky/">Martin Odersky</a>'
profpic: '/resources/img/profilepic.jpg'
profpic-retina: '/resources/img/profilepic@2x.jpg'
twitter: mehdiakbn
email: 'mehdi74akbarian@gmail.com'
github: 'makbn'
location: 'Calgary, AB, Canada'
location-url: "https://goo.gl/maps/tTXYvHFQ9rj6GyiLA"

# For syntax highlighting, the primary programming langauge you intend to use in
# blog articles. By default, Google's prettify will be used for this programming
# language, as per the instructions here: https://github.com/google/code-prettify
# For example, if I indicate `scala`, all pre/code blocks will have the `lang-scala`
# class added to the markup, triggering prettify to highlight the syntax as Scala.
primarylanguage: java
# To sidestep the default language for syntax highlighting set here, you can be
# explicit in your blog articles with the langauge you'd prefer to use. E.g.,
# <pre>
#   <code class="prettyprint lang-ruby">
#    ..ruby code here...
#   </code>
# </pre>

# categories:
#   blog:
#     permalink: /blog/:title.html

# Settings for blog RSS feed
name: "Mehdi Akbarian"
description: "I'm a graduate student and research assistant at the University of Alberta, Department of Computer Science. Formerly, I was a full-time software engineer at Fanap Co., where I worked with the titles of Technical Lead in Sakku Cloud Platform and Pod Space Cloud Storage. I started coding in middle school and, after a while, switched to Java in 2012. In my graduate studies, I worked with Prof. Rafiei on the Open Entity Resolution topic using transformer-based language models. During this time, I practiced a lot with Data mining and Machine learning techniques. I will graduate in December, 2022."
url: "https://makbn.giithub.io"

permalink: /:categories/:title.html
# markdown: redcarpet
highlighter: null

sass:
  style: compressed

livereload: true
